# build stage
FROM node:16-alpine as build-stage

WORKDIR /app

COPY app/package*.json /

RUN npm install

COPY app/ .

RUN npm run build

# production stage
FROM nginx:1.23-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/
COPY nginx/default.conf /etc/nginx/conf.d/

RUN adduser -G www-data -g www-data -s /bin/sh -D www-data

RUN chown www-data:www-data /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
